### ISSUE TITLE
Wichtig: Filterung funktioniert falsch

### ISSUE THREAD

**Issue by ruizcrp** [openZH/KRZH_gever#10]
Angenommen man sucht nach verschiedenen Geschäftsarten. Beispielsweise Interpellationen und Postulate. 
Dann wählt man diese entweder im Filter an, oder in der API gibt man die entsprechenden Geschäftsarten an.

Das gewünschte Resultat (sowohl auf der Website wie auch per API) wäre, dass sowohl Interpellationen wie Postulate angezeigt würden. 

Das eigentliche Resultat ist, dass Geschäfte angezeigt werden, die SOWOHL Interprellationen wie auch Postulate sind. Somit kann die Suche leer sein. (Nachprüfen kann man dies, indem man z.B. Interpellation und parlamentarische Initiative anwählt - hier gibt es Geschäfte die sowohl als auch sind). 

Technisch wahrscheinlich so: Statt einem ANY wird ein ALL irgendwo verwendet (oder statt einem ODER wird ein UND verwendet).

**Comment by angelanigg** [comment]
@FabianEllenberger oder @Jones-S 
Könntet ihr euch das anschauen? Ein entsprechendes Notion Ticket habe ich erstellt (vgl. KR 226)

**Comment by FabianEllenberger** [comment]
@ruizcrp und @angelanigg:

Aktuell requested die Webseite bei einer Filterung von der API ein `ANY`: `geschaeftsart any "Interpellation,Postulat"`.

Ganze Request: https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=geschaeftsart%20any%20%22Interpellation,Postulat%22%20sortBy%20beginn_start/sort.descending%20krnr/sort.descending&l=de-CH&s=1&m=50

Würde nach meinem Verständniss bedeuten, dass somit eigentlich Geschäfte mit der Geschäftsart «Interpellation» sowie auch «Postulate» angezeigt werden sollten. Ich habe den Request nun mit `ALL` und `ADJ` probiert und komme leider bei beiden Fällen zum gleichen leeren Resultat:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/6638067/144090476-ecbe93f1-147d-4db7-8662-877db63b27f4.png">


Laut CMI Dokumentation müsste der korrekte Reuqest mit einem `ADJ` gesetz werden:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/6638067/144090322-4b37bd89-0160-422d-9560-ceb1e08392d2.png">

Ich denke es macht hier Sinn CMI zu kontaktieren, um von ihnen die korrekte API Abfrage zu erhalten, oder zu prüfen, ob eventuell von der API bereits nicht die korrekten Einträge zurückkommen.

**Comment by klugemaurice** [comment]
Ihr habt die Antwort Euch oben bereits gegeben. Am Resultat ist erkennbar, ob der Query korrekt war. Zu Beachten ist, dass CQL in seiner Abfrage eingeschränkt ist. Es ist nicht mit den Feinheiten einer SQL abfrage ebenbürtig.

**Comment by klugemaurice** [comment]
Mögliche Operatoren

any | Der Feldinhalt muss mindestens einen der genannten   Suchbegriffe enthalten. Beispiel:   Vorstoesser any "Meier Müller Huber"   diese Abfrage findet den Vorstoesser "Heiri   Müller", aber nicht "Alfons Schneider".
-- | --
all | Der Feldinhalt muss alle genannten Suchbegriffe enthalten   Beispiel:   Vorstoesser all "Meier Anna"   diese Abfrage findet Vorstoesser "Meier Max und Anna   Theiler", aber nicht "Fridolin Meier".
adj | Der Feldinhalt muss die angegebene Wortfolge enthalten   ("Phrase Query") Beispiel:   Vorstoesser adj "Meier Anna"   diese Abfrage findet den Titel "Fridolin Meier Anna   Klauser", aber nicht "Fridolin Anna Meier Klauser"

**Comment by FabianEllenberger** [comment]
@klugemaurice Danke für deine Erläuterung. Ich habe daraus entnommen, dass unser Query «falsch» war, wir haben bisher bei diesem request die zu suchenden Queries mit Komma getrennt, z.B: `q=geschaeftsart any "Interpollation, Postulat"`. Eigentlich müsste es aber mit einem Leerschlag getrennt werden: `q=geschaeftsart any "Interpollation Postulat"`.

Ich habe das in unserer Testumgebung überprüft und folgendes Resultat erhalten:

Request:
https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=geschaeftsart%20any%20%22Interpellation%20Postulat%22%20sortBy%20beginn_start/sort.descending%20krnr/sort.descending&l=de-CH&s=1&m=50

Ausgabe im Frontend:
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/6638067/149804282-e88e9928-3162-4794-ab21-6bf275769895.png">

Wir bekommen nun nicht mehr 0 sondern 3081 Resultate. @angelanigg & @ruizcrp nun wäre es wichtig, dass wir prüfen ob dieses Resultat die korrekten Geschäfte beinhaltet (meiner Meinung nach ja). Soll ich diese Anpassung live schalten, damit ihr es gleich testen könnt, oder reicht euch die Request die ich oben verlinkt habe, bzw. der Screenshot? Zudem würden wir bei uns überprüfen, ob es noch andere Request bei der Filterung gibt, welche sich gleichermassen «falsch» verhalten und mit die @angelanigg anschauen.

**Comment by ruizcrp** [comment]
Hallo, herzlichen Dank für die Änderung! Das Screenshot sieht gut aus! Die Frage liegt zur Beantwortung wahrscheinlich bei @angelanigg , aber falls ihr es live schaltet, kann ich auch einen Blick darauf werfen.

**Comment by angelanigg** [comment]
Liebe alle
Vielen Dank für Eure Abklärungen und entschuldigt die späte Antwort. Ich denke die Anpassung ist nötig. Denn wenn die Sucherin auf der Website bspw. Postulate und Interpellationen in Kombination mit dem Stichwort "Finanzen" sucht, würde er mit der aktuellen Sucheinstellung keine Resultate erhalten, da es keine Geschäfte gibt, die sowohl "Interpellation" wie auch "Postulat" sein können. Beim Filter "Geschäftsart" müsste somit eingestellt werden, dass alle Geschäfte dieser Art in den Suchergebnissen aufgeführt werden sollten, die in der Filterauswahl angewählt wurden. Denn wenn eine Mehrfachauswahl bei der Geschäftsart möglich ist, müsste dies so geschehen, da die Sucherin wahrscheinlich intuitiv davon ausgeht.
Sollte dies nicht möglich sein, dürfte beim Filter Geschäftsart ansonsten keine Mehrfachauswahl ermöglicht werden.

**Comment by FabianEllenberger** [comment]
Liebe Angela

Danke für dein Update! Wir werden die Mehrfachauswahl entsprechend anpassen (wie im Screenshot oben).

> Liebe alle Vielen Dank für Eure Abklärungen und entschuldigt die späte Antwort. Ich denke die Anpassung ist nötig. Denn wenn die Sucherin auf der Website bspw. Postulate und Interpellationen in Kombination mit dem Stichwort "Finanzen" sucht, würde er mit der aktuellen Sucheinstellung keine Resultate erhalten, da es keine Geschäfte gibt, die sowohl "Interpellation" wie auch "Postulat" sein können. Beim Filter "Geschäftsart" müsste somit eingestellt werden, dass alle Geschäfte dieser Art in den Suchergebnissen aufgeführt werden sollten, die in der Filterauswahl angewählt wurden. Denn wenn eine Mehrfachauswahl bei der Geschäftsart möglich ist, müsste dies so geschehen, da die Sucherin wahrscheinlich intuitiv davon ausgeht. Sollte dies nicht möglich sein, dürfte beim Filter Geschäftsart ansonsten keine Mehrfachauswahl ermöglicht werden.

**Comment by adrupp** [comment]
@FabianEllenberger 
Was ist der Status dieses Issue? Kann es geschlossen werden?

**Comment by FabianEllenberger** [comment]
> @FabianEllenberger Was ist der Status dieses Issue? Kann es geschlossen werden?

Kann geschlossen werden, danke!
