### ISSUE TITLE
Wie funktioniert das Paging genau?

### ISSUE THREAD

**Issue by gutknecht** [openZH/KRZH_gever#11]
Ich möchte alle Geschäfte seit 2009 erhalten. Die Einschränkung mit Beginndatum ergibt aktuell 5814 Treffer. Mit einem Query werden max 1000 Geschäfte ausgegeben. Mein Versuch die Geschäfte via 6 Aufrufe mit Paging zu laden, scheitert jedoch, da der Paging Parmeter s=1, s=2 usw, jeweils die gleichen 1000 Geschäfte (wenn auch in einer anderen Reihenfolge) ausgibt. Wie bringe ich den Cursor vorwärts?

- https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=beginn_start+%3E+%222009-01-01+00%3A00%3A00%22+&l=de-CH&s=1&m=1000
- https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=beginn_start+%3E+%222009-01-01+00%3A00%3A00%22+&l=de-CH&s=2&m=1000

![image](https://user-images.githubusercontent.com/3227412/146277355-8e2548e3-c495-4b2a-b7f2-67acb21fa7c0.png)

**Comment by andreasamsler** [comment]
Liebe @angelanigg, kannst du mit Hilfe von @klugemaurice et al. die Frage von @gutknecht klären? Merci, lg Andreas

**Comment by angelanigg** [comment]
@gutknecht Bitte entschuldigen Sie die lange Wartezeit. Ich oder allenfalls @klugemaurice werden uns so schnell wie möglich mit einer Antwort melden!

**Comment by klugemaurice** [comment]
Für das Paging gibt es zwei elementare Parameter: s (startRecord) und m (maximumRecords) 
Der Parameter m hat ein Default- und Max-Wert von 1'000. Der Parameter muss aber nicht definiert werden, da in diesem Fall nicht eine Darstellung von 20 Treffern für eine WebSite benötigt wird, sonder alles abgeholt werden will, womit er so gross wie möglich sein soll. 
Wenn nun die Treffermenge (Im Element SearchDetailResponse, Attribut numHits) 1'000 übersteigt, werden in der ersten Suche 1'000 Elemente in der Trefferliste ausgegeben. Nun kann mit dem Parameter s eine zweite Suche gemacht werden, um die nächsten 1'000 Treffer zu erhalten. Der Parameter ist dann s=1001, was bedeutet, dass von der selben Trefferliste ab dem 1001ten Element die nächsten 1'000 verlangt werden. Die Abfrage wir sinngemäss solange wiederholt, bis die Gesamtzahl der Treffer (numHits) abgeholt wurden. In dem Beispiel oben wären das 6 (s=1, s=1001, s=2001, etc.) Durchläufe, bis die 5827 Treffern abgeholt sind.

**Comment by gutknecht** [comment]
Vielen Dank. Das funktioniert :-)

https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=beginn_start+%3E+%222009-01-01+00%3A00%3A00%22+&l=de-CH&s=1&m=1000
https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=beginn_start+%3E+%222009-01-01+00%3A00%3A00%22+&l=de-CH&s=1001&m=1000
https://parlzhcdws.cmicloud.ch/parlzh5/cdws/Index/GESCHAEFT/searchdetails?q=beginn_start+%3E+%222009-01-01+00%3A00%3A00%22+&l=de-CH&s=2001&m=1000
