### ISSUE TITLE
Behörden mit «oe», im Folgenode mit «o»

### ISSUE THREAD

**Issue by amslera** [openZH/KRZH_gever#7]
Issue gemeldet von @simonhuwiler

![5E79F240-C086-4495-910E-2468D22EB3C9](https://user-images.githubusercontent.com/65558323/140332479-2aceb571-61af-4e9e-b846-421fd64df726.png)

https://parlzhcdws.cmicloud.ch/parlzh2/cdws/Index/MITGLIEDER/searchdetails?q=seq%3E0%20and%20dauer_end%20%3E=%20%222020-11-19%2000:00:00%22%20and%20dauer_start%20%3C=%20%222020-11-19%2000:00:00%22%20and%20gremium%20all%20KR%20and%20funktion%20any%20%22Mitglied%20Präsidium%20Vizepräsidium%22%20sortBy%20name/sort.ascending%20vorname/sort.ascending&l=de-CH

**Comment by klugemaurice** [comment]
Dies ist ein Schreibfehler. Dieser kann aber nicht geändert werden, da sonst die Webpublikation nicht mehr funktioniert.

**Comment by angelanigg** [comment]
Lieber Herren Lucid @FabianEllenberger und @Jones-S
Herr Huwiler hat auf obenstehenden Schreibfehler aufmerksam gemacht. Maurice hat darauf hingewiesen, dass dessen Korrektur eine Anpassung eurerseits nötig  machen würde.  Wie schätzt ihr diesen Aufwand ein (vgl. Notion [KR] 223)?

**Comment by FabianEllenberger** [comment]
> Lieber Herren Lucid @FabianEllenberger und @Jones-S Herr Huwiler hat auf obenstehenden Schreibfehler aufmerksam gemacht. Maurice hat darauf hingewiesen, dass dessen Korrektur eine Anpassung eurerseits nötig machen würde. Wie schätzt ihr diesen Aufwand ein (vgl. Notion [KR] 223)?

Liebe Angela
Mir kommt dieser Schreibfehler bekannt vor, ich meinte sogar, dass wir dazu einen Kommentar im Code haben. Wir haben unsere Schätzung (inklusive Testing) im Notion [KR] 223 hinterlegt.

**Comment by klugemaurice** [comment]
Die Korrektur ist erfolgt.
