### ISSUE TITLE
Merkwürdige Daten: Amtsperiode

### ISSUE THREAD

**Issue by simonhuwiler** [openZH/KRZH_gever#8]
Liebe Kolleg:innen

Folgend Ergebnisse aus der Api, die ich nicht nachvollziehen kann: Aus der Kantonsrats-Api werden sämtliche Mitglieder und ihre Amtszeit geladen.

Die Adresse:
https://parlzhcdws.cmicloud.ch/parlzh2/cdws/Index/MITGLIEDER/searchdetails?q=seq%3E0%20and%20dauer_end%20%3E%3D%20%222000-11-19%2000%3A00%3A00%22%20and%20dauer_start%20%3C%3D%20%222022-12-31%2000%3A00%3A00%22%20and%20gremium%20all%20KR%20and%20funktion%20any%20%22Mitglied%20Pr%C3%A4sidium%20Vizepr%C3%A4sidium%22%20sortBy%20name/sort.ascending%20vorname/sort.ascending&l=de-CH

**Robert Brunner** war von 2004 bis 2020 Kantonsrat.

Im XML wird seine Amtsperiode (unter `Mitglied/Dauer`) angegeben als: *2020-02-01 - 2020-02-11*.
Unter `Behordenmandate/Behordenmandat/` GremiumTyp = Kantonsrat ebenfalls nur einmalig von 2020-02-01 - 2020-02-11.

Was überlege ich falsch?
![image](https://user-images.githubusercontent.com/38250965/140883905-2563bde8-01fc-4538-a9c4-473c2955f59b.png)

Liebe Grüsse
Ps. Diese Anfrage ging vor einer Woche auch per E-Mail raus. Bitte schaut doch Eure Mails an.

**Comment by andreasamsler** [comment]
Lieber @klugemaurice, kannst du die Frage von @simonhuwiler klären? Merci, lg Andreas

**Comment by klugemaurice** [comment]
Was ist den genau das Problem? Ist ja alles da.

**Comment by andreasamsler** [comment]
@klugemaurice ich verstehe @simonhuwiler's Frage so: Wo lässt sich "Robert Brunner war von 2004 bis 2020 Kantonsrat" auslesen?

**Comment by simonhuwiler** [comment]
Die Daten sagen, dass Robert Brunner 11 Tage lang Kantonsrat war (was nicht stimmt). Seine vergangenen Mandate (Kommissionen) werden zwar bis 2004 angezeigt, nicht jedoch, wie lange er eigentlich **Mitglied** des Kantonsrats war.

Die Fragen daher:
* Wieso werden alte Kommissions-Mandate angezeigt, nicht jedoch die Mitgliedschaft im Kantonsrat?
* Wie findet man heraus, wer wann **wirklich** in den Kantonsrat eintrat?

**Comment by klugemaurice** [comment]
Bitte wenden Sie sich an die Kanzlei. Für die Korrektheit der Daten sind wir nicht zuständig.

**Comment by andreasamsler** [comment]
Liebe @angelanigg, kannst du inhaltlich zur Klärung der Fragen https://github.com/openZH/KRZH_gever/issues/8#issuecomment-964029462 beitragen?

**Comment by angelanigg** [comment]
> Die Daten sagen, dass Robert Brunner 11 Tage lang Kantonsrat war (was nicht stimmt). Seine vergangenen Mandate (Kommissionen) werden zwar bis 2004 angezeigt, nicht jedoch, wie lange er eigentlich **Mitglied** des Kantonsrats war.
> 
> Die Fragen daher:
> 
> * Wieso werden alte Kommissions-Mandate angezeigt, nicht jedoch die Mitgliedschaft im Kantonsrat?
> * Wie findet man heraus, wer wann **wirklich** in den Kantonsrat eintrat?

Die falsche Mitgliedsdauer von Herr Brunner war ein Fehler in den Daten der Parlamentsdienste, bitte entschuldigen Sie Herr Huwiler.  Wir haben die Amtsdauer korrigiert. Herr Brunner war von 08.03.2004 bis am 10.02.2020 im Kantonsrat vgl.
https://www.kantonsrat.zh.ch/mitglieder/mitglied/?id=d01af08e64e24e5fa0e025e78f9d0eda
Die ehemaligen Kantonsratsmitglieder sind auf der Seite des Staatsarchivs des Kantons Zürich aufgeführt, vgl. https://www.zh.ch/de/politik-staat/wahlen-abstimmungen/kantons-regierungsratswahlen/mitglieder-kantonsrats-ab-1803.html

**Comment by simonhuwiler** [comment]
Danke fürs Abklären!
